C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\WpfApp1.exe
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\WpfApp1.deps.json
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\WpfApp1.runtimeconfig.json
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\WpfApp1.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\WpfApp1.pdb
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\Microsoft.Extensions.Logging.Abstractions.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\MySqlConnector.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\System.Windows.Extensions.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\bin\Debug\net9.0-windows\runtimes\win\lib\net9.0\System.Windows.Extensions.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.csproj.AssemblyReference.cache
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\MainWindow.baml
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\App.baml
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\MainWindow.g.cs
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\App.g.cs
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1_MarkupCompile.cache
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.g.resources
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.GeneratedMSBuildEditorConfig.editorconfig
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.AssemblyInfoInputs.cache
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.AssemblyInfo.cs
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.csproj.CoreCompileInputs.cache
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.csproj.Up2Date
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\refint\WpfApp1.dll
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.pdb
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\WpfApp1.genruntimeconfig.cache
C:\Users\Student\Documents\CyberBot_Part3\WpfApp1\obj\Debug\net9.0-windows\ref\WpfApp1.dll
